apiVersion: v1
kind: Service
metadata:
  name: counter-service
spec:
  type: NodePort
  selector:
    app: counter-service
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: external-name-service
spec:
  type: ExternalName
  externalName: counter-service.us-east-1.rds.amazonaws.com