output "cluster_id" {
  description = "EKS cluster ID."
  value = data.aws_eks_cluster.cluster.cluster_id
}


output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value = data.aws_eks_cluster.cluster.kubeconfig
}


output "region" {
  description = "AWS region"
  value = var.region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value = var.cluster_name
}

output "endpoint" {
  value = data.aws_eks_cluster.cluster.endpoint
}